on: [push]
name: Build and deploy on push
jobs:
  dockerhub_publish_main:
    name: DockerHub Build and Publish main
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build and Publish main to DockerHub
      uses: westonsteimel/action-docker-publish@main
      with:
        registry: 'docker.io'
        password: ${{ secrets.DOCKER_PASSWORD }}
        username: ${{ secrets.DOCKER_USERNAME }}
        image_name: 'nmap'
        build_context: '.'
        dockerfile_path: 'Dockerfile'
        tag_ref: false
        tag_latest: true
        tag_version: true
        tag_sha: false
        tag_timestamp: true

